### ISSUE TITLE
Error occurred when i run demo.py

### ISSUE THREAD

**Issue by longwayfather** [wtjiang98/PSGAN#35]
Traceback (most recent call last):
  File "/mnt/sdb/longwei.xu/PSGAN/demo.py", line 72, in <module>
    main()
  File "/mnt/sdb/longwei.xu/PSGAN/demo.py", line 57, in main
    image, face = inference.transfer(source, reference, with_face=True)
  File "/mnt/sdb/longwei.xu/PSGAN/psgan/inference.py", line 33, in transfer
    source_input, face, crop_face = self.preprocess(source)
  File "/mnt/sdb/longwei.xu/PSGAN/psgan/preprocess.py", line 141, in __call__
    mask = self.face_parse.parse(cv2.resize(np_image, (512, 512)))
  File "/mnt/sdb/longwei.xu/PSGAN/faceutils/mask/main.py", line 37, in parse
    parsing = torch.nn.functional.embedding(parsing, self.dic)
  File "/mnt/sdb/longwei.xu/anaconda3/lib/python3.9/site-packages/torch/nn/functional.py", line 2044, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: 'weight' must be 2-D

parse.shape:
torch.Size([512, 512])
parse 
tensor([[ 0,  0,  0,  ..., 17, 17, 17],
        [ 0,  0,  0,  ..., 17, 17, 17],
        [ 0,  0,  0,  ..., 17, 17, 17],
        ...,
        [17, 17, 17,  ..., 16, 16, 16],
        [17, 17, 17,  ..., 16, 16, 16],
        [17, 17, 17,  ..., 16, 16, 16]])

**Comment by vi-mahi** [comment]
Hello Iam also getting the same error.
Did you resolved this issue.
If solved send me the instructions please.

**Comment by longwayfather** [comment]
I'm so sorry that i didn't try to solve this error;
I tryed to use CPM to realize makeup transfer, maybe you can try to use it.(Although their code looks like patchwork...)




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wtjiang98/PSGAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月22日(星期六) 晚上9:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wtjiang98/PSGAN] Error occurred when i run demo.py (Issue #35)





 
Hello Iam also getting the same error.
 Did you resolved this issue.
 If solved send me the instructions please.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rdaim** [comment]
Hello I am also getting the same error. anybody can help me? thanks a lot

**Comment by kirylfb** [comment]
+1

**Comment by wtjiang98** [comment]
you can refer to #37
