### ISSUE TITLE
运行时出现以下问题，请问是什么原因？

### ISSUE THREAD

**Issue by starstars123** [wtjiang98/PSGAN#4]
G:\Anaconda3\python.exe G:/PSGAN-master/makeup/main.py
Traceback (most recent call last):
  File "G:/PSGAN-master/makeup/main.py", line 129, in <module>
    images = [preprocess(image) for image in images]
  File "G:/PSGAN-master/makeup/main.py", line 129, in <listcomp>
    images = [preprocess(image) for image in images]
  File "G:/PSGAN-master/makeup/main.py", line 69, in preprocess
    face = futils.dlib.detect(image)
  File "G:\PSGAN-master\faceutils\dlibutils\main.py", line 14, in detect
    return detector(np.asarray(image), 1)
RuntimeError: Expected writable numpy.ndarray with shape set.

Process finished with exit code 1

**Comment by wtjiang98** [comment]
Does it works with the default images? I think this error occur when you use your own images.
I suggest you to use images that have the same type and shape with default images.

**Comment by starstars123** [comment]
> Does it works with the default images? I think this error occur when you use your own images.
> I suggest you to use images that have the same type and shape with default images.

if __name__ == '__main__':
    # source image, reference image
    images = ['xfsy_0106.png', 'vFG586.png']
使用的应该就是默认图片，然后出现的这个错误，我用的windows系统下的pycharm运行的。

**Comment by wtjiang98** [comment]
@starstars123 Sorry, we did not test on Windows. Let me know if you solve the problem.

**Comment by vuexiaob** [comment]
Traceback (most recent call last):
  File "D:/devCode/PSGAN-master/demo.py", line 72, in <module>
    main()
  File "D:/devCode/PSGAN-master/demo.py", line 57, in main
    image, face = inference.transfer(source, reference, with_face=True)
  File "D:\devCode\PSGAN-master\psgan\inference.py", line 33, in transfer
    source_input, face, crop_face = self.preprocess(source)
  File "D:\devCode\PSGAN-master\psgan\preprocess.py", line 152, in __call__
    lms = futils.dlib.landmarks(image, face) * self.img_size / image.width
  File "D:\devCode\PSGAN-master\faceutils\dlibutils\main.py", line 111, in landmarks
    shape = predictor(np.asarray(image), face).parts()
RuntimeError: Expected writable numpy.ndarray with shape set.
